# Generated by Django 4.0 on 2022-01-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='MyPost',
        ),
    ]
